name: .NET Core

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    env:
      NUPKG_MAJOR: 2.2
      CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

   # - name: Test
   #   run: dotnet test --configuration Release
    - name: Package NuGets
      shell: pwsh
      run: |
        $VERSION="$env:NUPKG_MAJOR-ci$env:GITHUB_RUN_ID"
        if ($env:GITHUB_EVENT_NAME -eq "release") {
          $VERSION = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
        }
        echo "::set-output name=pkgverci::$VERSION"
        echo "PACKAGE VERSION: $VERSION"
        
        dotnet pack -p:PackageOutputPath=..\artifacts -p:Configuration=Release -p:PackageVersion=$VERSION .\MavenNet\MavenNet.csproj

        $pfxPath = Join-Path -Path $pwd -ChildPath "codesigncert.pfx"
        [IO.File]::WriteAllBytes("$pfxPath", [System.Convert]::FromBase64String($env:CODESIGN_PFX))
        dotnet nuget sign .\artifacts\*.nupkg --certificate-path $pfxPath --timestamper http://timestamp.entrust.net/TSS/RFC3161sha2TS
        
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet
        path: ./artifacts

  publish:
    name: Publish
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
      - name: Push NuGet
        run: |
          dotnet nuget push NuGet\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_ORG_API_KEY }}
